services:
  eventswebapplication.webapi:
    image: ${DOCKER_REGISTRY-}eventswebapplicationwebapi
    build:
      context: .
      dockerfile: EventsWebApplication.WebAPI/Dockerfile
    ports:
      - "8080:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=sqlserver;Database=EventsDb;User Id=sa;Password=YourStrongPassword123;TrustServerCertificate=true;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourStrongPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
