services:
  webapi:
    build:
      context: .
      dockerfile: EventsWebApplication.WebAPI/Dockerfile
    ports:
      - "5195:5195"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EventsDb;User Id=sa;Password=YourStrongPassword123!;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql 

volumes:
  sqlserverdata:
